# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-30 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='prof_pic',
            field=models.ImageField(blank=True, default=None, upload_to='profile/doctor/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='prof_pic',
            field=models.ImageField(blank=True, default=None, upload_to='profile/patient/'),
        ),
    ]
