# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_auto_20200828_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='kit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='corona.Status'),
            preserve_default=False,
        ),
    ]
