# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-30 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_auto_20200830_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='prof_pic',
            field=models.ImageField(upload_to='doctor/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prof_pic',
            field=models.ImageField(upload_to='patient/'),
        ),
    ]
