# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_auto_20200828_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
        migrations.RemoveField(
            model_name='report',
            name='treatment',
        ),
    ]
