# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-30 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_auto_20200830_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='location',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prof_pic',
            field=models.ImageField(blank=True, upload_to='doctor/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prof_pic',
            field=models.ImageField(blank=True, upload_to='patient/'),
        ),
    ]
