# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0004_auto_20200828_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='kit',
            field=models.CharField(max_length=100),
        ),
    ]
