# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-31 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0005_auto_20200831_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prof_pic',
            field=models.ImageField(blank=True, null=True, upload_to='patient/'),
        ),
    ]
