# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0006_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
