# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-01 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0006_auto_20200831_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
