# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-01 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0009_patient_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
