# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
