# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0010_auto_20200828_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='corona.Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='treatment',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='corona.Treatment'),
            preserve_default=False,
        ),
    ]
